### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Akumzy** [TheJaredWilcurt/vue-desktop-basic#1]
Am basically building a file syncing application with Electronjs which will be up on every startup how well can nw.js handles this better than Electron?

**Comment by TheJaredWilcurt** [comment]
@Akumzy 

The process would be basically the same, they both would rely on Node.js to handle file system interactions and monitoring. They can both use Node modules and run Node commands from the UI. They are both built on top of Chromium as well, so you will have access to the Chrome API, and able to use all the browser libraries and tools you are used to.

The difference between the two is that NW.js is a lighter, and more powerful choice. If you need access to a larger ecosystem, that is the primary benefit of Electron. NW.js is updated much faster and more often, so you will always have access to the latest Chromium and Node versions as soon as they come out. If you want to do source code protection, only NW.js supports that. NW.js will also support about twice as many operating systems as Electron. So if you need legacy support (Windows XP+, OSX 10.6+) it is a better choice. Also Electron does not really take Linux support seriously. NW.js works on most Debian based OS's (Debian, Ubuntu, Zorin, etc.). Here is a tutorial for getting started with NW.js, it is pretty easy to use.

* https://gitlab.com/TheJaredWilcurt/battery-app-workshop

If you do not care about the look of the app, and are fine with native elements, there is libui-node, though it is very new. This will still give you access to Node, but be smaller in file size due to not having to ship a browser with the app. Though, again, it is still very new and may not be ready for production use.

A commercial alternative would be Sciter. I do not have any experience with it yet, so can't speak to it's pros/cons.

**Comment by TheJaredWilcurt** [comment]
**Closing:**

1. There is now a very robust Vue + NW.js boilerplate:
   * https://github.com/nwutils/nw-vue3-boilerplate
1. If you are looking for NW.js or Electron alternatives:
   * https://xpda.net
